# Inspired by https://github.com/files-community/Files/blob/main/.github/workflows/cd-store-stable.yml

name: Pacenotes Installer Debug Build creator

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9 Preview
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Extract application version
      id: get_version
      run: |
        $file = Get-ChildItem -Path . -Filter '*.csproj' -Recurse | Select-Object -First 1
        if (-not $file) {
          Write-Error \"No .csproj file found in the repository.\"
          exit 1
        }
        $version = Select-String -Path $file.FullName -Pattern '<Version>(.*?)</Version>' | ForEach-Object { $_.Matches.Groups[1].Value }
        if (-not $version) {
          Write-Error \"Version tag not found in $($file.FullName).\"
          exit 1
        }
        echo "Application Version: $version"
        echo "VERSION=$version" >> $env:GITHUB_ENV

    # This isn't great, but I couldn't find a better way to embed strings from external sources into .net applications
    - name: Generate Secrets.resx file from environment variables
      run: |
        echo "Generating Secrets.resx from environment variables..."

        $envStrings = @"
          <root>
            <data name="publicKey" xml:space="preserve">
              <value>${{ secrets.SUPABASE_PUBLICKEY }}</value>
            </data>
            <data name="publicUrl" xml:space="preserve">
              <value>${{ secrets.SUPABASE_PUBLICURL }}</value>
            </data>
            <data name="privateKey" xml:space="preserve">
              <value>${{ secrets.SUPABASE_PUBLICURL }}</value>
            </data>
          </root>
        "@

        $envStrings | Out-File -FilePath Properties\Secrets.resx -Encoding UTF8

    - name: Build the application
      run: |
        dotnet publish /p:Configuration=Debug /p:PublishProfile=DebugProfile

    - name: Verify output
      shell: pwsh
      run: |
        if (-not(Test-path "bin\Debug\Pacenotes_Installer.exe" -PathType leaf)) {
          echo "Output file not found!"
          exit 1
        }

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pacenotes-installer-debug-build-v${{ env.VERSION }}
        path: bin/Debug
